version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "3000:3000" # Expose port 3000 for the React app
    volumes:
      - ./client:/usr/src/quest_ceadar/client # Mount the current directory to the container
    environment:
      - CHOKIDAR_USEPOLLING=true # Use polling for hot reloading
    depends_on:
      - server # Depend on the server service
    restart: always

  server:
    build: ./server
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - ./server:/usr/src/quest_ceadar
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=quest_ceadar
    restart: always

volumes:
  postgres_data:
    driver: local
